name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    description: Build and test across multiple Swift/Xcode versions
    strategy:
      matrix:
        include:
          - os: macos-15
            xcode: 16.4
          - os: macos-26
            xcode: 26.2
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - uses: actions/checkout@v5

      # Extract only mockolo from Mintfile to avoid installing unnecessary tools
      - name: Prepare Minimal Mintfile for Mockolo
        run: awk '/mockolo/{print; exit}' Mintfile > .github/Mintfile

      - uses: irgaly/setup-mint@v1
        with:
          mint-directory: .github

      - name: Generate mocks with Mockolo
        run: make gen-mocks

      - name: Build Swift package with tests
        run: swift build --build-tests

      - name: Run unit and integration tests
        run: swift test 2>&1 | xcbeautify
